name: Build Mod

# Trigger this workflow on push to the main branch or pull requests to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2  # Explicitly use v2 of actions/checkout

      # Set up JDK 8 for Gradle build
      - name: Set up JDK 8
        uses: actions/setup-java@v2  # Explicitly use v2 of actions/setup-java
        with:
          java-version: '8'  # Set Java 8 as required for building the mod

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3  # Explicitly use v3 of actions/cache
        with:
          path: ~/.gradle/caches  # Cache Gradle dependencies
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}  # Cache key
          restore-
