name: Build Mod

# Trigger this workflow on push to the main branch or pull requests to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository’s code

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'  # Set up Java 8 for building the mod

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build the mod with Gradle
        run: ./gradlew build  # Run the Gradle build command

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mod-jar
          path: build/libs/*.jar  # Upload the .jar file generated by Gradle
