name: Build Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 8 for Gradle build
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the mod using Gradle
      - name: Build the mod with Gradle
        run: ./gradlew build

      # Debug step to check if .jar exists in build/libs
      - name: List build/libs/ directory
        run: ls build/libs/

      # Upload the generated .jar file as an artifact
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mod-jar
          path: build/libs/*.jar
