name: Build Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      # Step 3: Cache Gradle dependencies to speed up builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Step 4: Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Step 5: List the build/libs/ directory to confirm the .jar exists
      - name: List build/libs/ directory
        run: ls -la build/libs/

      # Step 6: Upload Build Artifacts (only if .jar is present)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mod-jar
          path: build/libs/*.jar
